version: "3"
services:
  api-server:
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.docker
    ports:
      - 8090:8090
